apiVersion: apps/v1
kind: Deployment
metadata:
  name: routineservice
  namespace: mg
spec:
  selector:
    matchLabels:
      app: routineservice
      version: v1
  replicas: 2
  template:
    metadata:
      labels:
        app: routineservice
        version: v1
    spec:
      containers:
      - name: routineservice
        image: ghcr.io/maximemmjh/routineservice:master
        ports:
        - containerPort: 80